### ISSUE TITLE
[code-review] item.html

### ISSUE THREAD

**Issue by nurimeansworld** [tood21/starbucks_clone#2]
1. input을 submit하는 것이 아니라 form 태그를 생략해도 괜찮지 않을까 합니다. 만약 스크립트로 submit하실 생각이셨다면 무시해주세요ㅎㅎ..
https://github.com/tood21/starbucks_clone/blob/a599dae549b908783fef807bb7752ba3d1eb4e06/item.html#L61-L67
2. hover했을 때 NEW, 시즌 한정은 확대가 되지 않는 걸 보아 이 2개도 들어갈 html이 추가로 필요하다 생각합니다~
https://github.com/tood21/starbucks_clone/blob/a599dae549b908783fef807bb7752ba3d1eb4e06/item.html#L107-L110
3. 이 부분은 어디에 있을까요??
https://github.com/tood21/starbucks_clone/blob/a599dae549b908783fef807bb7752ba3d1eb4e06/item.html#L155-L159

**Comment by nurimeansworld** [comment]
https://github.com/tood21/starbucks_clone/blob/a599dae549b908783fef807bb7752ba3d1eb4e06/item.html#L23-L42
소메뉴와 주메뉴의 위치가 어떤 것이 위가 좋은지 고민
- 보통 다른 프로젝트 보면 주메뉴가 위로 가고 css로 소메뉴 위치를 수정하기도
- 하지만 주메뉴안의 메뉴들이 많아지면 스크린 리더기가 읽기 무거워서 소메뉴를 위로 하는 것이 좋지 않을까

**Comment by tood21** [comment]
닫아요~~
