### ISSUE TITLE
[code review_CSS]

### ISSUE THREAD

**Issue by Sangdon1029** [tood21/starbucks_clone#3]
## focus와 active를 같이 주신 이유가 궁금합니다.

https://github.com/tood21/starbucks_clone/blob/91b922c3f602e2987dc767dadba3b38888c6c07a/src/css/style.css#L27

**Comment by Sangdon1029** [comment]
## html 과 body에 직접 fontsize를 지정하신 이유가 있을까요?
- 혹시 전체를 설정 할 때  * 를 사용하지 않으신 이유가 있을까요? 

https://github.com/tood21/starbucks_clone/blob/91b922c3f602e2987dc767dadba3b38888c6c07a/src/css/style.css#L34

**Comment by tood21** [comment]
닫습니다~~
