### ISSUE TITLE
211219 코드리뷰(3)

### ISSUE THREAD

**Issue by nurimeansworld** [tood21/starbucks_clone#6]
1. btn-sort에 css로 화살표 위^인 이미지로 변경을 추가해주면 좋을 것 같습니다~
https://github.com/tood21/starbucks_clone/blob/dc6cf3bfb935dd39c9c2c606cce0d8a2b1f42f45/item.html#L279-L281
![image](https://user-images.githubusercontent.com/69141304/146666000-78848665-2d02-4d4f-a4b5-e747ace6dd33.png)
2. 배경색이 동일해서 border를 넣거나 조금 짙은 색으로 해주면 좋을 것 같습니다.
https://github.com/tood21/starbucks_clone/blob/dc6cf3bfb935dd39c9c2c606cce0d8a2b1f42f45/src/css/style.css#L230-L234
3. padding을 아래만 주지 않으신 이유가 궁금합니다.
https://github.com/tood21/starbucks_clone/blob/dc6cf3bfb935dd39c9c2c606cce0d8a2b1f42f45/src/css/style.css#L178-L184

**Comment by tood21** [comment]
닫아요
